from django.contrib import admin
from pilot.models import *

admin.site.register(Authority)
admin.site.register(ContactAddress)
admin.site.register(ContactDetailsRadiocommunications)
admin.site.register(ContactDetails)
admin.site.register(FeatureName)
admin.site.register(FixedDateRange)
admin.site.register(FrequencyPair)
admin.site.register(Information)
admin.site.register(NoticeTime)
admin.site.register(OnlineResource)
admin.site.register(PeriodicDateRange)
admin.site.register(Radiocommunications)
admin.site.register(ScheduleByDayOfWeek)
admin.site.register(ServiceHours)
admin.site.register(ShipReport)
admin.site.register(SourceIndication)
admin.site.register(Telecommunications)
admin.site.register(TextContent)
admin.site.register(TimeIntervalsByDayOfWeek)
